version: "3.8"

services:
  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Client:/app
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
